{
 "title": "New dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[30s])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "AverageTime für Berechnungen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "method_timed_seconds_sum/method_timed_seconds_count",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "status codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (http_server_requests_seconds_count{uri!~\"/actuator.*||/public.*||/token-info||root\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Größe der Listen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "primListSize", "legendFormat": "Size primList" },
    { "expr": "fibonacciListSize", "legendFormat": "Size fibonacciList" }
   ]
  },
  {
   "title": "Anzahl Primzahl Berechnungen",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "targets": [
    { "expr": "primService_total" }
   ]
  },
  {
   "title": "Anzahl Fibonaccizahl Berechnungen",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "targets": [
    { "expr": "fibonacciService_total" }
   ]
  }
 ]
}